# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pathway_api_graph_ql_development
  username: <%= Rails.application.credentials.dig(:development, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
  host: localhost
  port: 5432

test:
  <<: *default

production:
  <<: *default
  database: pathway_api_production
  username: <%= ENV["PATHWAY_API_DATABASE_USERNAME"] %>
  password: <%= ENV["PATHWAY_API_DATABASE_PASSWORD"] %>
  host: <%= ENV["PATHWAY_API_DATABASE_HOST"] %>
